import { OnInit, EventEmitter, Renderer2, ElementRef, ChangeDetectorRef } from '@angular/core';
import { Router } from '@angular/router';
import * as i0 from "@angular/core";
export declare class TablePanelComponent implements OnInit {
    private router;
    private render;
    private elRef;
    private cdr;
    scrollBarDirective: EventEmitter<any>;
    screenStatus: string;
    name: string;
    variant: boolean;
    noBody: boolean;
    noButton: boolean;
    bodyClass: boolean;
    footerClass: boolean;
    panelClass: boolean;
    panelFooter: any;
    expand: boolean;
    reload: boolean;
    collapse: boolean;
    remove: boolean;
    showFooter: boolean;
    pageName: string;
    clickToAddNew: boolean;
    ClicktoMaximize: ElementRef;
    ClicktoMinimize: ElementRef;
    constructor(router: Router, render: Renderer2, elRef: ElementRef, cdr: ChangeDetectorRef);
    ngOnInit(): void;
    ngAfterViewInit(): void;
    eventEmitToPageNaviagte: EventEmitter<string>;
    addNew(): void;
    panelExpandCollapse: EventEmitter<any>;
    panelExpand(): void;
    refreshTableList: EventEmitter<string>;
    panelReload(): void;
    panelCollapse(): void;
    panelRemove(): void;
    inpputSearchBoxElement: any;
    searchButton(dataSource?: any): void;
    searchButtonPanel(dataSource?: any): void;
    setTableDasourceAsDefault(dataSource: any): void;
    applyFilter(filterValue: any, dataSource: any): void;
    exportTable(tableName: any, fileName: any): void;
    static ɵfac: i0.ɵɵFactoryDef<TablePanelComponent>;
    static ɵcmp: i0.ɵɵComponentDefWithMeta<TablePanelComponent, "app-panel-user", never, { "name": "name"; "variant": "variant"; "noBody": "noBody"; "noButton": "noButton"; "bodyClass": "bodyClass"; "footerClass": "footerClass"; "panelClass": "panelClass"; }, { "scrollBarDirective": "scrollBarDirective"; "eventEmitToPageNaviagte": "eventEmitToPageNaviagte"; "panelExpandCollapse": "panelExpandCollapse"; "refreshTableList": "refreshTableList"; }, never>;
}
