import { DoCheck, ElementRef, EventEmitter, KeyValueDiffers, NgZone, OnChanges, OnDestroy, OnInit, SimpleChanges } from '@angular/core';
import PerfectScrollbar from 'perfect-scrollbar';
import { Geometry, PerfectScrollbarConfigInterface, Position } from './scroll-bar.interfaces';
import * as i0 from "@angular/core";
export declare class ScrollbarDirective implements OnInit, OnDestroy, DoCheck, OnChanges {
    private zone;
    private differs;
    elementRef: ElementRef;
    private platformId;
    private defaults;
    private el;
    private instance;
    private ro;
    private timeout;
    private animation;
    private configDiff;
    private readonly ngDestroy;
    disabled: boolean;
    config?: PerfectScrollbarConfigInterface;
    psScrollY: EventEmitter<any>;
    psScrollX: EventEmitter<any>;
    psScrollUp: EventEmitter<any>;
    psScrollDown: EventEmitter<any>;
    psScrollLeft: EventEmitter<any>;
    psScrollRight: EventEmitter<any>;
    psYReachEnd: EventEmitter<any>;
    psYReachStart: EventEmitter<any>;
    psXReachEnd: EventEmitter<any>;
    psXReachStart: EventEmitter<any>;
    constructor(zone: NgZone, differs: KeyValueDiffers, elementRef: ElementRef, platformId: Object, defaults: PerfectScrollbarConfigInterface, el: ElementRef);
    ngOnInit(): void;
    ngOnDestroy(): void;
    ngDoCheck(): void;
    ngOnChanges(changes: SimpleChanges): void;
    ps(): PerfectScrollbar | null;
    update(): void;
    geometry(prefix?: string): Geometry;
    position(absolute?: boolean): Position;
    scrollable(direction?: string): boolean;
    scrollTo(x: number, y?: number, speed?: number): void;
    scrollToX(x: number, speed?: number): void;
    scrollToY(y: number, speed?: number): void;
    scrollToTop(offset?: number, speed?: number): void;
    scrollToLeft(offset?: number, speed?: number): void;
    scrollToRight(offset?: number, speed?: number): void;
    scrollToBottom(offset?: number, speed?: number): void;
    scrollToElement(qs: string, offset?: number, speed?: number): void;
    private animateScrolling;
    onClick(event: Event): void;
    scrollPositionToTop(): void;
    static ɵfac: i0.ɵɵFactoryDef<ScrollbarDirective>;
    static ɵdir: i0.ɵɵDirectiveDefWithMeta<ScrollbarDirective, "[appScrollbarDirective]", ["ngxPerfectScrollbar"], { "disabled": "disabled"; "config": "perfectScrollbar"; }, { "psScrollY": "psScrollY"; "psScrollX": "psScrollX"; "psScrollUp": "psScrollUp"; "psScrollDown": "psScrollDown"; "psScrollLeft": "psScrollLeft"; "psScrollRight": "psScrollRight"; "psYReachEnd": "psYReachEnd"; "psYReachStart": "psYReachStart"; "psXReachEnd": "psXReachEnd"; "psXReachStart": "psXReachStart"; }, never>;
}
